// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcgX3MkqklGCLl7ZfQlXhc6Z9toTOxvsE',
    appId: '1:575384841806:web:0b3223d457921392125d1f',
    messagingSenderId: '575384841806',
    projectId: 'spotshare-bccee',
    authDomain: 'spotshare-bccee.firebaseapp.com',
    storageBucket: 'spotshare-bccee.firebasestorage.app',
    measurementId: 'G-3W1LGHXXZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfvlKzByVURKmWERa17CgRSFzPcUNeUM4',
    appId: '1:575384841806:android:1493efd9e8036744125d1f',
    messagingSenderId: '575384841806',
    projectId: 'spotshare-bccee',
    storageBucket: 'spotshare-bccee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtu8Xu9-Me7sr9qCqrAAGkWeDKfGIo9pQ',
    appId: '1:575384841806:ios:4e1d2c3b66b57c0f125d1f',
    messagingSenderId: '575384841806',
    projectId: 'spotshare-bccee',
    storageBucket: 'spotshare-bccee.firebasestorage.app',
    iosBundleId: 'com.example.spotShare2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtu8Xu9-Me7sr9qCqrAAGkWeDKfGIo9pQ',
    appId: '1:575384841806:ios:4e1d2c3b66b57c0f125d1f',
    messagingSenderId: '575384841806',
    projectId: 'spotshare-bccee',
    storageBucket: 'spotshare-bccee.firebasestorage.app',
    iosBundleId: 'com.example.spotShare2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcgX3MkqklGCLl7ZfQlXhc6Z9toTOxvsE',
    appId: '1:575384841806:web:fe54d279eca8cf28125d1f',
    messagingSenderId: '575384841806',
    projectId: 'spotshare-bccee',
    authDomain: 'spotshare-bccee.firebaseapp.com',
    storageBucket: 'spotshare-bccee.firebasestorage.app',
    measurementId: 'G-XF8ZSF4W01',
  );
}
